# https://pnpm.io/ja/continuous-integration#github-actions
name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: ci
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: setup dotenvx keys
      env:
        DOTENV_PRIVATE_KEY_VARS: ${{ secrets.DOTENV_PRIVATE_KEY_VARS }}
      run: |
        echo DOTENV_PRIVATE_KEY_VARS=${{ env.DOTENV_PRIVATE_KEY_VARS }} >> .env.keys
    - run: pnpm install
    - run: pnpm run check:tsc
    - run: pnpm run check:biome
    - run: npx vitest --coverage.enabled true
    - name: Report vitest coverage
      uses:  davelosert/vitest-coverage-report-action@v2
