name: production-deploy
on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_URL: "https://fujimatsu.tsar-bmb.org/"

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: production-deploy

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: setup dotenvx keys
        env:
          DOTENV_PRIVATE_KEY_VARS: ${{ secrets.DOTENV_PRIVATE_KEY_VARS }}
        run: |
          echo DOTENV_PRIVATE_KEY_VARS=${{ env.DOTENV_PRIVATE_KEY_VARS }} >> .env.keys
      - run: pnpm install
      - name: deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: production
          packageManager: pnpm
          secrets: |
            NODE_ENV
            DISCORD_OAUTH_BASE_URL
            DISCORD_ID
            DISCORD_SECRET
            DISCORD_REDIRECT_URL
        env:
          NODE_ENV: production
          DISCORD_OAUTH_BASE_URL: "https://discord.com/api/oauth2"
          DISCORD_ID: ${{ secrets.DISCORD_ID }}
          DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
          DISCORD_REDIRECT_URL: ${{env.DEPLOYMENT_URL}}

  health-check:
    name: health check
    needs: production-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{env.DEPLOYMENT_URL}}
          max-attempts: 3
          retry-delay: 10s
